'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace AppService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AppService.IGlobalService")>  _
    Public Interface IGlobalService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGlobalService/ExecuteSQL", ReplyAction:="http://tempuri.org/IGlobalService/ExecuteSQLResponse")>  _
        Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGlobalService/ExecuteSQL", ReplyAction:="http://tempuri.org/IGlobalService/ExecuteSQLResponse")>  _
        Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGlobalService/ExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IGlobalService/ExecuteSQLNonQueryResponse")>  _
        Function ExecuteSQLNonQuery(ByVal QueryString As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGlobalService/ExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IGlobalService/ExecuteSQLNonQueryResponse")>  _
        Function ExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IGlobalServiceChannel
        Inherits AppService.IGlobalService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GlobalServiceClient
        Inherits System.ServiceModel.ClientBase(Of AppService.IGlobalService)
        Implements AppService.IGlobalService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet Implements AppService.IGlobalService.ExecuteSQL
            Return MyBase.Channel.ExecuteSQL(QueryString)
        End Function
        
        Public Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements AppService.IGlobalService.ExecuteSQLAsync
            Return MyBase.Channel.ExecuteSQLAsync(QueryString)
        End Function
        
        Public Function ExecuteSQLNonQuery(ByVal QueryString As String) As Boolean Implements AppService.IGlobalService.ExecuteSQLNonQuery
            Return MyBase.Channel.ExecuteSQLNonQuery(QueryString)
        End Function
        
        Public Function ExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Boolean) Implements AppService.IGlobalService.ExecuteSQLNonQueryAsync
            Return MyBase.Channel.ExecuteSQLNonQueryAsync(QueryString)
        End Function
    End Class
End Namespace
