'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace MailBotServiceWCF
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InputConfiguration", [Namespace]:="http://schemas.datacontract.org/2004/07/MailBot.Entidades"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InputConfiguration
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateUpdateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdInputConfigurationField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdInputTypeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMessageConfigurationField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InputConfigurationDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcessFileField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserCreateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserUpdateField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreate() As Date
            Get
                Return Me.DateCreateField
            End Get
            Set
                If (Me.DateCreateField.Equals(value) <> true) Then
                    Me.DateCreateField = value
                    Me.RaisePropertyChanged("DateCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateUpdate() As Date
            Get
                Return Me.DateUpdateField
            End Get
            Set
                If (Me.DateUpdateField.Equals(value) <> true) Then
                    Me.DateUpdateField = value
                    Me.RaisePropertyChanged("DateUpdate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdInputConfiguration() As Integer
            Get
                Return Me.IdInputConfigurationField
            End Get
            Set
                If (Me.IdInputConfigurationField.Equals(value) <> true) Then
                    Me.IdInputConfigurationField = value
                    Me.RaisePropertyChanged("IdInputConfiguration")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdInputType() As Integer
            Get
                Return Me.IdInputTypeField
            End Get
            Set
                If (Me.IdInputTypeField.Equals(value) <> true) Then
                    Me.IdInputTypeField = value
                    Me.RaisePropertyChanged("IdInputType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMessageConfiguration() As Integer
            Get
                Return Me.IdMessageConfigurationField
            End Get
            Set
                If (Me.IdMessageConfigurationField.Equals(value) <> true) Then
                    Me.IdMessageConfigurationField = value
                    Me.RaisePropertyChanged("IdMessageConfiguration")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InputConfigurationDescription() As String
            Get
                Return Me.InputConfigurationDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InputConfigurationDescriptionField, value) <> true) Then
                    Me.InputConfigurationDescriptionField = value
                    Me.RaisePropertyChanged("InputConfigurationDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProcessFile() As String
            Get
                Return Me.ProcessFileField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProcessFileField, value) <> true) Then
                    Me.ProcessFileField = value
                    Me.RaisePropertyChanged("ProcessFile")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserCreate() As String
            Get
                Return Me.UserCreateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserCreateField, value) <> true) Then
                    Me.UserCreateField = value
                    Me.RaisePropertyChanged("UserCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserUpdate() As String
            Get
                Return Me.UserUpdateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserUpdateField, value) <> true) Then
                    Me.UserUpdateField = value
                    Me.RaisePropertyChanged("UserUpdate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InputSubject", [Namespace]:="http://schemas.datacontract.org/2004/07/MailBot.Entidades"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InputSubject
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateUpdateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMessageConfigurationField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMessageSubjectField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubjectIdentifierField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserCreateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserUpdateField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreate() As Date
            Get
                Return Me.DateCreateField
            End Get
            Set
                If (Me.DateCreateField.Equals(value) <> true) Then
                    Me.DateCreateField = value
                    Me.RaisePropertyChanged("DateCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateUpdate() As Date
            Get
                Return Me.DateUpdateField
            End Get
            Set
                If (Me.DateUpdateField.Equals(value) <> true) Then
                    Me.DateUpdateField = value
                    Me.RaisePropertyChanged("DateUpdate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMessageConfiguration() As Integer
            Get
                Return Me.IdMessageConfigurationField
            End Get
            Set
                If (Me.IdMessageConfigurationField.Equals(value) <> true) Then
                    Me.IdMessageConfigurationField = value
                    Me.RaisePropertyChanged("IdMessageConfiguration")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMessageSubject() As Integer
            Get
                Return Me.IdMessageSubjectField
            End Get
            Set
                If (Me.IdMessageSubjectField.Equals(value) <> true) Then
                    Me.IdMessageSubjectField = value
                    Me.RaisePropertyChanged("IdMessageSubject")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubjectIdentifier() As String
            Get
                Return Me.SubjectIdentifierField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubjectIdentifierField, value) <> true) Then
                    Me.SubjectIdentifierField = value
                    Me.RaisePropertyChanged("SubjectIdentifier")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserCreate() As String
            Get
                Return Me.UserCreateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserCreateField, value) <> true) Then
                    Me.UserCreateField = value
                    Me.RaisePropertyChanged("UserCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserUpdate() As String
            Get
                Return Me.UserUpdateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserUpdateField, value) <> true) Then
                    Me.UserUpdateField = value
                    Me.RaisePropertyChanged("UserUpdate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InputType", [Namespace]:="http://schemas.datacontract.org/2004/07/MailBot.Entidades"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InputType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateUpdateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdInputTypeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InputTypeDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserCreateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserUpdateField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreate() As Date
            Get
                Return Me.DateCreateField
            End Get
            Set
                If (Me.DateCreateField.Equals(value) <> true) Then
                    Me.DateCreateField = value
                    Me.RaisePropertyChanged("DateCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateUpdate() As Date
            Get
                Return Me.DateUpdateField
            End Get
            Set
                If (Me.DateUpdateField.Equals(value) <> true) Then
                    Me.DateUpdateField = value
                    Me.RaisePropertyChanged("DateUpdate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdInputType() As Integer
            Get
                Return Me.IdInputTypeField
            End Get
            Set
                If (Me.IdInputTypeField.Equals(value) <> true) Then
                    Me.IdInputTypeField = value
                    Me.RaisePropertyChanged("IdInputType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InputTypeDescription() As String
            Get
                Return Me.InputTypeDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InputTypeDescriptionField, value) <> true) Then
                    Me.InputTypeDescriptionField = value
                    Me.RaisePropertyChanged("InputTypeDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserCreate() As String
            Get
                Return Me.UserCreateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserCreateField, value) <> true) Then
                    Me.UserCreateField = value
                    Me.RaisePropertyChanged("UserCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserUpdate() As String
            Get
                Return Me.UserUpdateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserUpdateField, value) <> true) Then
                    Me.UserUpdateField = value
                    Me.RaisePropertyChanged("UserUpdate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MessageConfiguration", [Namespace]:="http://schemas.datacontract.org/2004/07/MailBot.Entidades"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MessageConfiguration
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AttachedFilesField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BlindCopyRecipientsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CopyRecipientsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomizedQueryField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateUpdateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdInputTypeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMessageConfigurationField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageFileField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RecipientsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserCreateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserUpdateField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AttachedFiles() As Byte()
            Get
                Return Me.AttachedFilesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AttachedFilesField, value) <> true) Then
                    Me.AttachedFilesField = value
                    Me.RaisePropertyChanged("AttachedFiles")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BlindCopyRecipients() As String
            Get
                Return Me.BlindCopyRecipientsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BlindCopyRecipientsField, value) <> true) Then
                    Me.BlindCopyRecipientsField = value
                    Me.RaisePropertyChanged("BlindCopyRecipients")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CopyRecipients() As String
            Get
                Return Me.CopyRecipientsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CopyRecipientsField, value) <> true) Then
                    Me.CopyRecipientsField = value
                    Me.RaisePropertyChanged("CopyRecipients")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomizedQuery() As String
            Get
                Return Me.CustomizedQueryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomizedQueryField, value) <> true) Then
                    Me.CustomizedQueryField = value
                    Me.RaisePropertyChanged("CustomizedQuery")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreate() As Date
            Get
                Return Me.DateCreateField
            End Get
            Set
                If (Me.DateCreateField.Equals(value) <> true) Then
                    Me.DateCreateField = value
                    Me.RaisePropertyChanged("DateCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateUpdate() As Date
            Get
                Return Me.DateUpdateField
            End Get
            Set
                If (Me.DateUpdateField.Equals(value) <> true) Then
                    Me.DateUpdateField = value
                    Me.RaisePropertyChanged("DateUpdate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdInputType() As Integer
            Get
                Return Me.IdInputTypeField
            End Get
            Set
                If (Me.IdInputTypeField.Equals(value) <> true) Then
                    Me.IdInputTypeField = value
                    Me.RaisePropertyChanged("IdInputType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMessageConfiguration() As Integer
            Get
                Return Me.IdMessageConfigurationField
            End Get
            Set
                If (Me.IdMessageConfigurationField.Equals(value) <> true) Then
                    Me.IdMessageConfigurationField = value
                    Me.RaisePropertyChanged("IdMessageConfiguration")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Image() As Byte()
            Get
                Return Me.ImageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageField, value) <> true) Then
                    Me.ImageField = value
                    Me.RaisePropertyChanged("Image")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImageFile() As Byte()
            Get
                Return Me.ImageFileField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageFileField, value) <> true) Then
                    Me.ImageFileField = value
                    Me.RaisePropertyChanged("ImageFile")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Recipients() As String
            Get
                Return Me.RecipientsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RecipientsField, value) <> true) Then
                    Me.RecipientsField = value
                    Me.RaisePropertyChanged("Recipients")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserCreate() As String
            Get
                Return Me.UserCreateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserCreateField, value) <> true) Then
                    Me.UserCreateField = value
                    Me.RaisePropertyChanged("UserCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserUpdate() As String
            Get
                Return Me.UserUpdateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserUpdateField, value) <> true) Then
                    Me.UserUpdateField = value
                    Me.RaisePropertyChanged("UserUpdate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MessageLayout", [Namespace]:="http://schemas.datacontract.org/2004/07/MailBot.Entidades"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MessageLayout
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateUpdateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdInputConfigurationField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMessageLayoutField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMessageStructureField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageTextField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserCreateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserUpdateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValidFromField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValidToField As System.Nullable(Of Date)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreate() As System.Nullable(Of Date)
            Get
                Return Me.DateCreateField
            End Get
            Set
                If (Me.DateCreateField.Equals(value) <> true) Then
                    Me.DateCreateField = value
                    Me.RaisePropertyChanged("DateCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateUpdate() As System.Nullable(Of Date)
            Get
                Return Me.DateUpdateField
            End Get
            Set
                If (Me.DateUpdateField.Equals(value) <> true) Then
                    Me.DateUpdateField = value
                    Me.RaisePropertyChanged("DateUpdate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdInputConfiguration() As Integer
            Get
                Return Me.IdInputConfigurationField
            End Get
            Set
                If (Me.IdInputConfigurationField.Equals(value) <> true) Then
                    Me.IdInputConfigurationField = value
                    Me.RaisePropertyChanged("IdInputConfiguration")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMessageLayout() As Integer
            Get
                Return Me.IdMessageLayoutField
            End Get
            Set
                If (Me.IdMessageLayoutField.Equals(value) <> true) Then
                    Me.IdMessageLayoutField = value
                    Me.RaisePropertyChanged("IdMessageLayout")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMessageStructure() As Integer
            Get
                Return Me.IdMessageStructureField
            End Get
            Set
                If (Me.IdMessageStructureField.Equals(value) <> true) Then
                    Me.IdMessageStructureField = value
                    Me.RaisePropertyChanged("IdMessageStructure")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MessageText() As String
            Get
                Return Me.MessageTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageTextField, value) <> true) Then
                    Me.MessageTextField = value
                    Me.RaisePropertyChanged("MessageText")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserCreate() As String
            Get
                Return Me.UserCreateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserCreateField, value) <> true) Then
                    Me.UserCreateField = value
                    Me.RaisePropertyChanged("UserCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserUpdate() As String
            Get
                Return Me.UserUpdateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserUpdateField, value) <> true) Then
                    Me.UserUpdateField = value
                    Me.RaisePropertyChanged("UserUpdate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ValidFrom() As System.Nullable(Of Date)
            Get
                Return Me.ValidFromField
            End Get
            Set
                If (Me.ValidFromField.Equals(value) <> true) Then
                    Me.ValidFromField = value
                    Me.RaisePropertyChanged("ValidFrom")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ValidTo() As System.Nullable(Of Date)
            Get
                Return Me.ValidToField
            End Get
            Set
                If (Me.ValidToField.Equals(value) <> true) Then
                    Me.ValidToField = value
                    Me.RaisePropertyChanged("ValidTo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MessageStructure", [Namespace]:="http://schemas.datacontract.org/2004/07/MailBot.Entidades"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MessageStructure
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateUpdateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMessageStructureField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IndexLocationField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageStructureDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SignatureField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserCreateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserUpdateField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreate() As Date
            Get
                Return Me.DateCreateField
            End Get
            Set
                If (Me.DateCreateField.Equals(value) <> true) Then
                    Me.DateCreateField = value
                    Me.RaisePropertyChanged("DateCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateUpdate() As Date
            Get
                Return Me.DateUpdateField
            End Get
            Set
                If (Me.DateUpdateField.Equals(value) <> true) Then
                    Me.DateUpdateField = value
                    Me.RaisePropertyChanged("DateUpdate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMessageStructure() As Integer
            Get
                Return Me.IdMessageStructureField
            End Get
            Set
                If (Me.IdMessageStructureField.Equals(value) <> true) Then
                    Me.IdMessageStructureField = value
                    Me.RaisePropertyChanged("IdMessageStructure")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IndexLocation() As Integer
            Get
                Return Me.IndexLocationField
            End Get
            Set
                If (Me.IndexLocationField.Equals(value) <> true) Then
                    Me.IndexLocationField = value
                    Me.RaisePropertyChanged("IndexLocation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MessageStructureDescription() As String
            Get
                Return Me.MessageStructureDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageStructureDescriptionField, value) <> true) Then
                    Me.MessageStructureDescriptionField = value
                    Me.RaisePropertyChanged("MessageStructureDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Signature() As Boolean
            Get
                Return Me.SignatureField
            End Get
            Set
                If (Me.SignatureField.Equals(value) <> true) Then
                    Me.SignatureField = value
                    Me.RaisePropertyChanged("Signature")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserCreate() As String
            Get
                Return Me.UserCreateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserCreateField, value) <> true) Then
                    Me.UserCreateField = value
                    Me.RaisePropertyChanged("UserCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserUpdate() As String
            Get
                Return Me.UserUpdateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserUpdateField, value) <> true) Then
                    Me.UserUpdateField = value
                    Me.RaisePropertyChanged("UserUpdate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="MailBotServiceWCF.IMailBotServicesWCF")>  _
    Public Interface IMailBotServicesWCF
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/ExecuteSQL", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/ExecuteSQLResponse")>  _
        Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/ExecuteSQL", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/ExecuteSQLResponse")>  _
        Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/NewExecuteSQL", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/NewExecuteSQLResponse")>  _
        Function NewExecuteSQL(ByVal QueryString As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/NewExecuteSQL", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/NewExecuteSQLResponse")>  _
        Function NewExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/ExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/ExecuteSQLNonQueryResponse")>  _
        Function ExecuteSQLNonQuery(ByVal QueryString As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/ExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/ExecuteSQLNonQueryResponse")>  _
        Function ExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/NewExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/NewExecuteSQLNonQueryResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MailBotServiceWCF.InputConfiguration)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MailBotServiceWCF.InputConfiguration())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MailBotServiceWCF.InputSubject)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MailBotServiceWCF.InputSubject())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MailBotServiceWCF.InputType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MailBotServiceWCF.InputType())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MailBotServiceWCF.MessageConfiguration)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MailBotServiceWCF.MessageConfiguration())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MailBotServiceWCF.MessageLayout)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MailBotServiceWCF.MessageLayout())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MailBotServiceWCF.MessageStructure)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MailBotServiceWCF.MessageStructure())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function NewExecuteSQLNonQuery(ByVal QueryString As String) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/NewExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/NewExecuteSQLNonQueryResponse")>  _
        Function NewExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/InsertInputConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/InsertInputConfigurationResponse")>  _
        Sub InsertInputConfiguration(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/InsertInputConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/InsertInputConfigurationResponse")>  _
        Function InsertInputConfigurationAsync(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/UpdateInputConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/UpdateInputConfigurationResponse")>  _
        Sub UpdateInputConfiguration(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/UpdateInputConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/UpdateInputConfigurationResponse")>  _
        Function UpdateInputConfigurationAsync(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/DeleteInputConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/DeleteInputConfigurationResponse")>  _
        Sub DeleteInputConfiguration(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/DeleteInputConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/DeleteInputConfigurationResponse")>  _
        Function DeleteInputConfigurationAsync(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllInputConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllInputConfigurationResponse")>  _
        Function GetAllInputConfiguration(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) As MailBotServiceWCF.InputConfiguration()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllInputConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllInputConfigurationResponse")>  _
        Function GetAllInputConfigurationAsync(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) As System.Threading.Tasks.Task(Of MailBotServiceWCF.InputConfiguration())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableInputConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableInputConfigurationResponse")>  _
        Function GetAllDataTableInputConfiguration(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableInputConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableInputConfigurationResponse")>  _
        Function GetAllDataTableInputConfigurationAsync(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/InsertInputSubject", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/InsertInputSubjectResponse")>  _
        Sub InsertInputSubject(ByVal oInputSubject As MailBotServiceWCF.InputSubject)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/InsertInputSubject", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/InsertInputSubjectResponse")>  _
        Function InsertInputSubjectAsync(ByVal oInputSubject As MailBotServiceWCF.InputSubject) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/UpdateInputSubject", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/UpdateInputSubjectResponse")>  _
        Sub UpdateInputSubject(ByVal oInputSubject As MailBotServiceWCF.InputSubject)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/UpdateInputSubject", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/UpdateInputSubjectResponse")>  _
        Function UpdateInputSubjectAsync(ByVal oInputSubject As MailBotServiceWCF.InputSubject) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/DeleteInputSubject", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/DeleteInputSubjectResponse")>  _
        Sub DeleteInputSubject(ByVal oInputSubject As MailBotServiceWCF.InputSubject)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/DeleteInputSubject", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/DeleteInputSubjectResponse")>  _
        Function DeleteInputSubjectAsync(ByVal oInputSubject As MailBotServiceWCF.InputSubject) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllInputSubject", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllInputSubjectResponse")>  _
        Function GetAllInputSubject(ByVal oInputSubject As MailBotServiceWCF.InputSubject) As MailBotServiceWCF.InputSubject()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllInputSubject", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllInputSubjectResponse")>  _
        Function GetAllInputSubjectAsync(ByVal oInputSubject As MailBotServiceWCF.InputSubject) As System.Threading.Tasks.Task(Of MailBotServiceWCF.InputSubject())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableInputSubject", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableInputSubjectResponse")>  _
        Function GetAllDataTableInputSubject(ByVal oInputSubject As MailBotServiceWCF.InputSubject) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableInputSubject", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableInputSubjectResponse")>  _
        Function GetAllDataTableInputSubjectAsync(ByVal oInputSubject As MailBotServiceWCF.InputSubject) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/InsertInputType", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/InsertInputTypeResponse")>  _
        Sub InsertInputType(ByVal oInputType As MailBotServiceWCF.InputType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/InsertInputType", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/InsertInputTypeResponse")>  _
        Function InsertInputTypeAsync(ByVal oInputType As MailBotServiceWCF.InputType) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/UpdateInputType", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/UpdateInputTypeResponse")>  _
        Sub UpdateInputType(ByVal oInputType As MailBotServiceWCF.InputType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/UpdateInputType", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/UpdateInputTypeResponse")>  _
        Function UpdateInputTypeAsync(ByVal oInputType As MailBotServiceWCF.InputType) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/DeleteInputType", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/DeleteInputTypeResponse")>  _
        Sub DeleteInputType(ByVal oInputType As MailBotServiceWCF.InputType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/DeleteInputType", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/DeleteInputTypeResponse")>  _
        Function DeleteInputTypeAsync(ByVal oInputType As MailBotServiceWCF.InputType) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllInputType", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllInputTypeResponse")>  _
        Function GetAllInputType(ByVal oInputType As MailBotServiceWCF.InputType) As MailBotServiceWCF.InputType()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllInputType", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllInputTypeResponse")>  _
        Function GetAllInputTypeAsync(ByVal oInputType As MailBotServiceWCF.InputType) As System.Threading.Tasks.Task(Of MailBotServiceWCF.InputType())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableInputType", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableInputTypeResponse")>  _
        Function GetAllDataTableInputType(ByVal oInputType As MailBotServiceWCF.InputType) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableInputType", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableInputTypeResponse")>  _
        Function GetAllDataTableInputTypeAsync(ByVal oInputType As MailBotServiceWCF.InputType) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/InsertMessageConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/InsertMessageConfigurationResponse")>  _
        Sub InsertMessageConfiguration(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/InsertMessageConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/InsertMessageConfigurationResponse")>  _
        Function InsertMessageConfigurationAsync(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/UpdateMessageConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/UpdateMessageConfigurationResponse")>  _
        Sub UpdateMessageConfiguration(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/UpdateMessageConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/UpdateMessageConfigurationResponse")>  _
        Function UpdateMessageConfigurationAsync(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/DeleteMessageConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/DeleteMessageConfigurationResponse")>  _
        Sub DeleteMessageConfiguration(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/DeleteMessageConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/DeleteMessageConfigurationResponse")>  _
        Function DeleteMessageConfigurationAsync(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllMessageConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllMessageConfigurationResponse")>  _
        Function GetAllMessageConfiguration(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) As MailBotServiceWCF.MessageConfiguration()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllMessageConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllMessageConfigurationResponse")>  _
        Function GetAllMessageConfigurationAsync(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) As System.Threading.Tasks.Task(Of MailBotServiceWCF.MessageConfiguration())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableMessageConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableMessageConfigurationRespons"& _ 
            "e")>  _
        Function GetAllDataTableMessageConfiguration(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableMessageConfiguration", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableMessageConfigurationRespons"& _ 
            "e")>  _
        Function GetAllDataTableMessageConfigurationAsync(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/InsertMessageLayout", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/InsertMessageLayoutResponse")>  _
        Sub InsertMessageLayout(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/InsertMessageLayout", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/InsertMessageLayoutResponse")>  _
        Function InsertMessageLayoutAsync(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/UpdateMessageLayout", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/UpdateMessageLayoutResponse")>  _
        Sub UpdateMessageLayout(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/UpdateMessageLayout", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/UpdateMessageLayoutResponse")>  _
        Function UpdateMessageLayoutAsync(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/DeleteMessageLayout", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/DeleteMessageLayoutResponse")>  _
        Sub DeleteMessageLayout(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/DeleteMessageLayout", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/DeleteMessageLayoutResponse")>  _
        Function DeleteMessageLayoutAsync(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllMessageLayout", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllMessageLayoutResponse")>  _
        Function GetAllMessageLayout(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) As MailBotServiceWCF.MessageLayout()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllMessageLayout", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllMessageLayoutResponse")>  _
        Function GetAllMessageLayoutAsync(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) As System.Threading.Tasks.Task(Of MailBotServiceWCF.MessageLayout())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableMessageLayout", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableMessageLayoutResponse")>  _
        Function GetAllDataTableMessageLayout(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableMessageLayout", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableMessageLayoutResponse")>  _
        Function GetAllDataTableMessageLayoutAsync(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/InsertMessageStructure", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/InsertMessageStructureResponse")>  _
        Sub InsertMessageStructure(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/InsertMessageStructure", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/InsertMessageStructureResponse")>  _
        Function InsertMessageStructureAsync(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/UpdateMessageStructure", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/UpdateMessageStructureResponse")>  _
        Sub UpdateMessageStructure(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/UpdateMessageStructure", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/UpdateMessageStructureResponse")>  _
        Function UpdateMessageStructureAsync(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/DeleteMessageStructure", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/DeleteMessageStructureResponse")>  _
        Sub DeleteMessageStructure(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/DeleteMessageStructure", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/DeleteMessageStructureResponse")>  _
        Function DeleteMessageStructureAsync(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllMessageStructure", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllMessageStructureResponse")>  _
        Function GetAllMessageStructure(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) As MailBotServiceWCF.MessageStructure()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllMessageStructure", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllMessageStructureResponse")>  _
        Function GetAllMessageStructureAsync(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) As System.Threading.Tasks.Task(Of MailBotServiceWCF.MessageStructure())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableMessageStructure", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableMessageStructureResponse")>  _
        Function GetAllDataTableMessageStructure(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableMessageStructure", ReplyAction:="http://tempuri.org/IMailBotServicesWCF/GetAllDataTableMessageStructureResponse")>  _
        Function GetAllDataTableMessageStructureAsync(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) As System.Threading.Tasks.Task(Of System.Data.DataTable)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IMailBotServicesWCFChannel
        Inherits MailBotServiceWCF.IMailBotServicesWCF, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MailBotServicesWCFClient
        Inherits System.ServiceModel.ClientBase(Of MailBotServiceWCF.IMailBotServicesWCF)
        Implements MailBotServiceWCF.IMailBotServicesWCF
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet Implements MailBotServiceWCF.IMailBotServicesWCF.ExecuteSQL
            Return MyBase.Channel.ExecuteSQL(QueryString)
        End Function
        
        Public Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements MailBotServiceWCF.IMailBotServicesWCF.ExecuteSQLAsync
            Return MyBase.Channel.ExecuteSQLAsync(QueryString)
        End Function
        
        Public Function NewExecuteSQL(ByVal QueryString As String) As System.Data.DataSet Implements MailBotServiceWCF.IMailBotServicesWCF.NewExecuteSQL
            Return MyBase.Channel.NewExecuteSQL(QueryString)
        End Function
        
        Public Function NewExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements MailBotServiceWCF.IMailBotServicesWCF.NewExecuteSQLAsync
            Return MyBase.Channel.NewExecuteSQLAsync(QueryString)
        End Function
        
        Public Function ExecuteSQLNonQuery(ByVal QueryString As String) As Boolean Implements MailBotServiceWCF.IMailBotServicesWCF.ExecuteSQLNonQuery
            Return MyBase.Channel.ExecuteSQLNonQuery(QueryString)
        End Function
        
        Public Function ExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Boolean) Implements MailBotServiceWCF.IMailBotServicesWCF.ExecuteSQLNonQueryAsync
            Return MyBase.Channel.ExecuteSQLNonQueryAsync(QueryString)
        End Function
        
        Public Function NewExecuteSQLNonQuery(ByVal QueryString As String) As Object() Implements MailBotServiceWCF.IMailBotServicesWCF.NewExecuteSQLNonQuery
            Return MyBase.Channel.NewExecuteSQLNonQuery(QueryString)
        End Function
        
        Public Function NewExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Object()) Implements MailBotServiceWCF.IMailBotServicesWCF.NewExecuteSQLNonQueryAsync
            Return MyBase.Channel.NewExecuteSQLNonQueryAsync(QueryString)
        End Function
        
        Public Sub InsertInputConfiguration(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) Implements MailBotServiceWCF.IMailBotServicesWCF.InsertInputConfiguration
            MyBase.Channel.InsertInputConfiguration(oInputConfiguration)
        End Sub
        
        Public Function InsertInputConfigurationAsync(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.InsertInputConfigurationAsync
            Return MyBase.Channel.InsertInputConfigurationAsync(oInputConfiguration)
        End Function
        
        Public Sub UpdateInputConfiguration(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) Implements MailBotServiceWCF.IMailBotServicesWCF.UpdateInputConfiguration
            MyBase.Channel.UpdateInputConfiguration(oInputConfiguration)
        End Sub
        
        Public Function UpdateInputConfigurationAsync(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.UpdateInputConfigurationAsync
            Return MyBase.Channel.UpdateInputConfigurationAsync(oInputConfiguration)
        End Function
        
        Public Sub DeleteInputConfiguration(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) Implements MailBotServiceWCF.IMailBotServicesWCF.DeleteInputConfiguration
            MyBase.Channel.DeleteInputConfiguration(oInputConfiguration)
        End Sub
        
        Public Function DeleteInputConfigurationAsync(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.DeleteInputConfigurationAsync
            Return MyBase.Channel.DeleteInputConfigurationAsync(oInputConfiguration)
        End Function
        
        Public Function GetAllInputConfiguration(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) As MailBotServiceWCF.InputConfiguration() Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllInputConfiguration
            Return MyBase.Channel.GetAllInputConfiguration(oInputConfiguration)
        End Function
        
        Public Function GetAllInputConfigurationAsync(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) As System.Threading.Tasks.Task(Of MailBotServiceWCF.InputConfiguration()) Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllInputConfigurationAsync
            Return MyBase.Channel.GetAllInputConfigurationAsync(oInputConfiguration)
        End Function
        
        Public Function GetAllDataTableInputConfiguration(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) As System.Data.DataTable Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllDataTableInputConfiguration
            Return MyBase.Channel.GetAllDataTableInputConfiguration(oInputConfiguration)
        End Function
        
        Public Function GetAllDataTableInputConfigurationAsync(ByVal oInputConfiguration As MailBotServiceWCF.InputConfiguration) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllDataTableInputConfigurationAsync
            Return MyBase.Channel.GetAllDataTableInputConfigurationAsync(oInputConfiguration)
        End Function
        
        Public Sub InsertInputSubject(ByVal oInputSubject As MailBotServiceWCF.InputSubject) Implements MailBotServiceWCF.IMailBotServicesWCF.InsertInputSubject
            MyBase.Channel.InsertInputSubject(oInputSubject)
        End Sub
        
        Public Function InsertInputSubjectAsync(ByVal oInputSubject As MailBotServiceWCF.InputSubject) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.InsertInputSubjectAsync
            Return MyBase.Channel.InsertInputSubjectAsync(oInputSubject)
        End Function
        
        Public Sub UpdateInputSubject(ByVal oInputSubject As MailBotServiceWCF.InputSubject) Implements MailBotServiceWCF.IMailBotServicesWCF.UpdateInputSubject
            MyBase.Channel.UpdateInputSubject(oInputSubject)
        End Sub
        
        Public Function UpdateInputSubjectAsync(ByVal oInputSubject As MailBotServiceWCF.InputSubject) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.UpdateInputSubjectAsync
            Return MyBase.Channel.UpdateInputSubjectAsync(oInputSubject)
        End Function
        
        Public Sub DeleteInputSubject(ByVal oInputSubject As MailBotServiceWCF.InputSubject) Implements MailBotServiceWCF.IMailBotServicesWCF.DeleteInputSubject
            MyBase.Channel.DeleteInputSubject(oInputSubject)
        End Sub
        
        Public Function DeleteInputSubjectAsync(ByVal oInputSubject As MailBotServiceWCF.InputSubject) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.DeleteInputSubjectAsync
            Return MyBase.Channel.DeleteInputSubjectAsync(oInputSubject)
        End Function
        
        Public Function GetAllInputSubject(ByVal oInputSubject As MailBotServiceWCF.InputSubject) As MailBotServiceWCF.InputSubject() Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllInputSubject
            Return MyBase.Channel.GetAllInputSubject(oInputSubject)
        End Function
        
        Public Function GetAllInputSubjectAsync(ByVal oInputSubject As MailBotServiceWCF.InputSubject) As System.Threading.Tasks.Task(Of MailBotServiceWCF.InputSubject()) Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllInputSubjectAsync
            Return MyBase.Channel.GetAllInputSubjectAsync(oInputSubject)
        End Function
        
        Public Function GetAllDataTableInputSubject(ByVal oInputSubject As MailBotServiceWCF.InputSubject) As System.Data.DataTable Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllDataTableInputSubject
            Return MyBase.Channel.GetAllDataTableInputSubject(oInputSubject)
        End Function
        
        Public Function GetAllDataTableInputSubjectAsync(ByVal oInputSubject As MailBotServiceWCF.InputSubject) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllDataTableInputSubjectAsync
            Return MyBase.Channel.GetAllDataTableInputSubjectAsync(oInputSubject)
        End Function
        
        Public Sub InsertInputType(ByVal oInputType As MailBotServiceWCF.InputType) Implements MailBotServiceWCF.IMailBotServicesWCF.InsertInputType
            MyBase.Channel.InsertInputType(oInputType)
        End Sub
        
        Public Function InsertInputTypeAsync(ByVal oInputType As MailBotServiceWCF.InputType) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.InsertInputTypeAsync
            Return MyBase.Channel.InsertInputTypeAsync(oInputType)
        End Function
        
        Public Sub UpdateInputType(ByVal oInputType As MailBotServiceWCF.InputType) Implements MailBotServiceWCF.IMailBotServicesWCF.UpdateInputType
            MyBase.Channel.UpdateInputType(oInputType)
        End Sub
        
        Public Function UpdateInputTypeAsync(ByVal oInputType As MailBotServiceWCF.InputType) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.UpdateInputTypeAsync
            Return MyBase.Channel.UpdateInputTypeAsync(oInputType)
        End Function
        
        Public Sub DeleteInputType(ByVal oInputType As MailBotServiceWCF.InputType) Implements MailBotServiceWCF.IMailBotServicesWCF.DeleteInputType
            MyBase.Channel.DeleteInputType(oInputType)
        End Sub
        
        Public Function DeleteInputTypeAsync(ByVal oInputType As MailBotServiceWCF.InputType) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.DeleteInputTypeAsync
            Return MyBase.Channel.DeleteInputTypeAsync(oInputType)
        End Function
        
        Public Function GetAllInputType(ByVal oInputType As MailBotServiceWCF.InputType) As MailBotServiceWCF.InputType() Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllInputType
            Return MyBase.Channel.GetAllInputType(oInputType)
        End Function
        
        Public Function GetAllInputTypeAsync(ByVal oInputType As MailBotServiceWCF.InputType) As System.Threading.Tasks.Task(Of MailBotServiceWCF.InputType()) Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllInputTypeAsync
            Return MyBase.Channel.GetAllInputTypeAsync(oInputType)
        End Function
        
        Public Function GetAllDataTableInputType(ByVal oInputType As MailBotServiceWCF.InputType) As System.Data.DataTable Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllDataTableInputType
            Return MyBase.Channel.GetAllDataTableInputType(oInputType)
        End Function
        
        Public Function GetAllDataTableInputTypeAsync(ByVal oInputType As MailBotServiceWCF.InputType) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllDataTableInputTypeAsync
            Return MyBase.Channel.GetAllDataTableInputTypeAsync(oInputType)
        End Function
        
        Public Sub InsertMessageConfiguration(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) Implements MailBotServiceWCF.IMailBotServicesWCF.InsertMessageConfiguration
            MyBase.Channel.InsertMessageConfiguration(oMessageConfiguration)
        End Sub
        
        Public Function InsertMessageConfigurationAsync(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.InsertMessageConfigurationAsync
            Return MyBase.Channel.InsertMessageConfigurationAsync(oMessageConfiguration)
        End Function
        
        Public Sub UpdateMessageConfiguration(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) Implements MailBotServiceWCF.IMailBotServicesWCF.UpdateMessageConfiguration
            MyBase.Channel.UpdateMessageConfiguration(oMessageConfiguration)
        End Sub
        
        Public Function UpdateMessageConfigurationAsync(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.UpdateMessageConfigurationAsync
            Return MyBase.Channel.UpdateMessageConfigurationAsync(oMessageConfiguration)
        End Function
        
        Public Sub DeleteMessageConfiguration(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) Implements MailBotServiceWCF.IMailBotServicesWCF.DeleteMessageConfiguration
            MyBase.Channel.DeleteMessageConfiguration(oMessageConfiguration)
        End Sub
        
        Public Function DeleteMessageConfigurationAsync(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.DeleteMessageConfigurationAsync
            Return MyBase.Channel.DeleteMessageConfigurationAsync(oMessageConfiguration)
        End Function
        
        Public Function GetAllMessageConfiguration(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) As MailBotServiceWCF.MessageConfiguration() Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllMessageConfiguration
            Return MyBase.Channel.GetAllMessageConfiguration(oMessageConfiguration)
        End Function
        
        Public Function GetAllMessageConfigurationAsync(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) As System.Threading.Tasks.Task(Of MailBotServiceWCF.MessageConfiguration()) Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllMessageConfigurationAsync
            Return MyBase.Channel.GetAllMessageConfigurationAsync(oMessageConfiguration)
        End Function
        
        Public Function GetAllDataTableMessageConfiguration(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) As System.Data.DataTable Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllDataTableMessageConfiguration
            Return MyBase.Channel.GetAllDataTableMessageConfiguration(oMessageConfiguration)
        End Function
        
        Public Function GetAllDataTableMessageConfigurationAsync(ByVal oMessageConfiguration As MailBotServiceWCF.MessageConfiguration) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllDataTableMessageConfigurationAsync
            Return MyBase.Channel.GetAllDataTableMessageConfigurationAsync(oMessageConfiguration)
        End Function
        
        Public Sub InsertMessageLayout(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) Implements MailBotServiceWCF.IMailBotServicesWCF.InsertMessageLayout
            MyBase.Channel.InsertMessageLayout(oMessageLayout)
        End Sub
        
        Public Function InsertMessageLayoutAsync(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.InsertMessageLayoutAsync
            Return MyBase.Channel.InsertMessageLayoutAsync(oMessageLayout)
        End Function
        
        Public Sub UpdateMessageLayout(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) Implements MailBotServiceWCF.IMailBotServicesWCF.UpdateMessageLayout
            MyBase.Channel.UpdateMessageLayout(oMessageLayout)
        End Sub
        
        Public Function UpdateMessageLayoutAsync(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.UpdateMessageLayoutAsync
            Return MyBase.Channel.UpdateMessageLayoutAsync(oMessageLayout)
        End Function
        
        Public Sub DeleteMessageLayout(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) Implements MailBotServiceWCF.IMailBotServicesWCF.DeleteMessageLayout
            MyBase.Channel.DeleteMessageLayout(oMessageLayout)
        End Sub
        
        Public Function DeleteMessageLayoutAsync(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.DeleteMessageLayoutAsync
            Return MyBase.Channel.DeleteMessageLayoutAsync(oMessageLayout)
        End Function
        
        Public Function GetAllMessageLayout(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) As MailBotServiceWCF.MessageLayout() Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllMessageLayout
            Return MyBase.Channel.GetAllMessageLayout(oMessageLayout)
        End Function
        
        Public Function GetAllMessageLayoutAsync(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) As System.Threading.Tasks.Task(Of MailBotServiceWCF.MessageLayout()) Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllMessageLayoutAsync
            Return MyBase.Channel.GetAllMessageLayoutAsync(oMessageLayout)
        End Function
        
        Public Function GetAllDataTableMessageLayout(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) As System.Data.DataTable Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllDataTableMessageLayout
            Return MyBase.Channel.GetAllDataTableMessageLayout(oMessageLayout)
        End Function
        
        Public Function GetAllDataTableMessageLayoutAsync(ByVal oMessageLayout As MailBotServiceWCF.MessageLayout) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllDataTableMessageLayoutAsync
            Return MyBase.Channel.GetAllDataTableMessageLayoutAsync(oMessageLayout)
        End Function
        
        Public Sub InsertMessageStructure(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) Implements MailBotServiceWCF.IMailBotServicesWCF.InsertMessageStructure
            MyBase.Channel.InsertMessageStructure(oMessageStructure)
        End Sub
        
        Public Function InsertMessageStructureAsync(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.InsertMessageStructureAsync
            Return MyBase.Channel.InsertMessageStructureAsync(oMessageStructure)
        End Function
        
        Public Sub UpdateMessageStructure(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) Implements MailBotServiceWCF.IMailBotServicesWCF.UpdateMessageStructure
            MyBase.Channel.UpdateMessageStructure(oMessageStructure)
        End Sub
        
        Public Function UpdateMessageStructureAsync(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.UpdateMessageStructureAsync
            Return MyBase.Channel.UpdateMessageStructureAsync(oMessageStructure)
        End Function
        
        Public Sub DeleteMessageStructure(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) Implements MailBotServiceWCF.IMailBotServicesWCF.DeleteMessageStructure
            MyBase.Channel.DeleteMessageStructure(oMessageStructure)
        End Sub
        
        Public Function DeleteMessageStructureAsync(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) As System.Threading.Tasks.Task Implements MailBotServiceWCF.IMailBotServicesWCF.DeleteMessageStructureAsync
            Return MyBase.Channel.DeleteMessageStructureAsync(oMessageStructure)
        End Function
        
        Public Function GetAllMessageStructure(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) As MailBotServiceWCF.MessageStructure() Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllMessageStructure
            Return MyBase.Channel.GetAllMessageStructure(oMessageStructure)
        End Function
        
        Public Function GetAllMessageStructureAsync(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) As System.Threading.Tasks.Task(Of MailBotServiceWCF.MessageStructure()) Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllMessageStructureAsync
            Return MyBase.Channel.GetAllMessageStructureAsync(oMessageStructure)
        End Function
        
        Public Function GetAllDataTableMessageStructure(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) As System.Data.DataTable Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllDataTableMessageStructure
            Return MyBase.Channel.GetAllDataTableMessageStructure(oMessageStructure)
        End Function
        
        Public Function GetAllDataTableMessageStructureAsync(ByVal oMessageStructure As MailBotServiceWCF.MessageStructure) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements MailBotServiceWCF.IMailBotServicesWCF.GetAllDataTableMessageStructureAsync
            Return MyBase.Channel.GetAllDataTableMessageStructureAsync(oMessageStructure)
        End Function
    End Class
End Namespace
